### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by lowoa** [quasemago/CSGO_WeaponStickers#10]
It does not work for me. 
I have the latest version of sourcemod.

22:26:34 L 09/06/2020 - 22:26:34: [SM] Exception reported: Native is not bound
22:26:34 L 09/06/2020 - 22:26:34: [SM] Blaming: csgo_weaponstickers.smx
22:26:34 L 09/06/2020 - 22:26:34: [SM] Call stack trace:
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [0] MemoryBlock.MemoryBlock
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [1] Line 165, quasemago/csgo_weaponstickers/helpers.inc::SetAttributeValue
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [2] Line 270, C:\Users\xd\Desktop\new(7)\addons\sourcemod\scripting\csgo_weaponstickers.sp::SetWeaponSticker
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [3] Line 228, C:\Users\xd\Desktop\new(7)\addons\sourcemod\scripting\csgo_weaponstickers.sp::OnGiveNamedItemPost
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [5] GivePlayerItem
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [6] Line 331, tmp/addons/sourcemod/scripting/weapons.sp::RefreshWeapon
22:26:34 L 09/06/2020 - 22:26:34: [SM]   [7] Line 39, tmp/addons/sourcemod/scripting/weapons/menus.sp::WeaponsMenuHandler

**Comment by quasemago** [comment]
You just have to read your own message and you will know the problem.

> Exception reported: Native is not bound

Source Scramble is not installed. Install all dependencies!!!!!!!!!!
