### ISSUE TITLE
Getting a error when i try to load the plugin

### ISSUE THREAD

**Issue by diasdiGhetto** [quasemago/CSGO_WeaponStickers#12]
I am getting this when i try to load the plugin

![transferir](https://user-images.githubusercontent.com/47485734/92925424-5f24a280-f432-11ea-878d-ecc01cc174f2.png)

**Comment by quasemago** [comment]
Install all depenencies. 🤦‍♂️

**Comment by diasdiGhetto** [comment]
yes my fault, thanks for the help
