### ISSUE TITLE
Sticker sumindo para flag 'a'

### ISSUE THREAD

**Issue by thegilaraujo** [quasemago/CSGO_WeaponStickers#15]
Boa noite amigo, como você havia dito no post do forum alliedmods estou usando sim o tVip e sourcebans para restringir os comandos !sticker, será que este é o verdadeiro problema?

**Comment by quasemago** [comment]
Provavelmente sim, tente adicionar a flag diretamente pelo "admins_simple.ini" e veja se funciona. Se funcionar você terá que editar o plugin para carregar o sticker apenas depois do tVip.

**Comment by thegilaraujo** [comment]
> Provavelmente sim, tente adicionar a flag diretamente pelo "admins_simple.ini" e veja se funciona. Se funcionar você terá que editar o plugin para carregar o sticker apenas depois do tVip (posso te auxiliar nisso).

Vou fazer isso agora e já entro em contato com você novamente.

**Comment by thegilaraujo** [comment]
Como você havia dito, adicionei uma steamID no "admins_simple.ini" e o adesivo manteve mesmo dando retry no servidor, após isso tirei o steamID novamente e o adesivo sumiu.
Como proceder agora?

**Comment by quasemago** [comment]
Você terá que editar o plugin e compilar, na linha 170:
https://github.com/quasemago/CSGO_WeaponStickers/blob/master/addons/sourcemod/scripting/csgo_weaponstickers.sp#L170

Adicione a forward do tVip logo abaixo da forward **OnClientPostAdminCheck**, vai ficar:
```
public void OnClientPostAdminCheck(int client)
{
	if (!g_cvarEnabled.BoolValue || IsFakeClient(client))
	{
		return;
	}

	LoadClientData(client);
}

public void tVip_OnClientLoadedPost(int client)
{
	if (!g_cvarEnabled.BoolValue || IsFakeClient(client))
	{
		return;
	}

	LoadClientData(client);
}
```

Isso irá carregar o sticker do jogador após ele receber a flag do tVip.

**Comment by thegilaraujo** [comment]
Boa tarde! Irei testar e assim que tiver resposta irei postar aqui.

Gostaria de fazer uma pergunta que foge um pouco do assunto...como aprendeu a dominar o sourcemod? Fez alguim tipo de curso? Algo do tipo? Estou enferrujado na programação, mas quero voltar agora e gostaria de aprender mais sobre essa biblioteca que é o SourceMod.

Poderia me dar uma dica? Obrigado desde já!

**Comment by zeisaac** [comment]
Amigo, instalei tudo e consigo colocar os adesivos, porem quando saio e entro no server nao fica salvo os adesivos colocados... como posso resolver esse problema? nao consigo criar um database SQL, tem algum link de youtube ou algo que possa me ajudar? grato!

**Comment by thegilaraujo** [comment]
> Amigo, instalei tudo e consigo colocar os adesivos, porem quando saio e entro no server nao fica salvo os adesivos colocados... como posso resolver esse problema? nao consigo criar um database SQL, tem algum link de youtube ou algo que possa me ajudar? grato!

Não consegue criar um database para o plugin em questão? Você deve ter isso aqui no "databases.cfg"


```
	"csgo_weaponstickers"
    {
        "driver"            "mysql"
        "host"                "localhost"
        "database"            "nomedb"
        "user"                "login"
        "pass"                "senhadb"
        //"timeout"            "0"
        "port"                "3306"
    }
```

**Comment by zeisaac** [comment]
> > Amigo, instalei tudo e consigo colocar os adesivos, porem quando saio e entro no server nao fica salvo os adesivos colocados... como posso resolver esse problema? nao consigo criar um database SQL, tem algum link de youtube ou algo que possa me ajudar? grato!
> 
> Não consegue criar um database para o plugin em questão? Você deve ter isso aqui no "databases.cfg"
> 
> ```
> 	"csgo_weaponstickers"
>     {
>         "driver"            "mysql"
>         "host"                "localhost"
>         "database"            "nomedb"
>         "user"                "login"
>         "pass"                "senhadb"
>         //"timeout"            "0"
>         "port"                "3306"
>     }
> ```

eu coloquei no database, porem fica aparecendo essa msg.
Connection to database failed: Could not find driver "mysql"

**Comment by thegilaraujo** [comment]
> > > Amigo, instalei tudo e consigo colocar os adesivos, porem quando saio e entro no server nao fica salvo os adesivos colocados... como posso resolver esse problema? nao consigo criar um database SQL, tem algum link de youtube ou algo que possa me ajudar? grato!
> > 
> > 
> > Não consegue criar um database para o plugin em questão? Você deve ter isso aqui no "databases.cfg"
> > ```
> > 	"csgo_weaponstickers"
> >     {
> >         "driver"            "mysql"
> >         "host"                "localhost"
> >         "database"            "nomedb"
> >         "user"                "login"
> >         "pass"                "senhadb"
> >         //"timeout"            "0"
> >         "port"                "3306"
> >     }
> > ```
> 
> eu coloquei no database, porem fica aparecendo essa msg.
> Connection to database failed: Could not find driver "mysql"

**Comment by thegilaraujo** [comment]
@zeisaac Você possui um banco de dados no seu servidor?

**Comment by zeisaac** [comment]
> @zeisaac Você possui um banco de dados no seu servidor?

Não ... tem que ser no servidor ou pode fazer um externo tipo no HostGator? Não entendo muito dessa questão do banco de dados. Me guia por favor!

**Comment by thegilaraujo** [comment]
> > @zeisaac Você possui um banco de dados no seu servidor?
> 
> Não ... tem que ser no servidor ou pode fazer um externo tipo no HostGator? Não entendo muito dessa questão do banco de dados. Me guia por favor!

Então, você precisa sim de um servidor de banco de dados para esse tipo de plugin, seu servidor é alugado? Com certeza ele tem um servidor de banco de dados. Procure saber primeiro sobre isso.

**Comment by zeisaac** [comment]
> > > @zeisaac Você possui um banco de dados no seu servidor?
> > 
> > 
> > Não ... tem que ser no servidor ou pode fazer um externo tipo no HostGator? Não entendo muito dessa questão do banco de dados. Me guia por favor!
> 
> Então, você precisa sim de um servidor de banco de dados para esse tipo de plugin, seu servidor é alugado? Com certeza ele tem um servidor de banco de dados. Procure saber primeiro sobre isso.

Meu servidor, eu mesmo criei no Google cloud... tá rodando tudo liso a um bom tempo. Então acredito que não tenha um servidor de banco de dados... e agora?

**Comment by thegilaraujo** [comment]
> Meu servidor, eu mesmo criei no Google cloud... tá rodando tudo liso a um bom tempo. Então acredito que não tenha um servidor de banco de dados... e agora?

Entendi, bom, eu não sei como funciona o sistema de Google Cloud, se quiser me adicionar no discord **gil#7351** para a gente conversar, a gente pode descobrir juntos

**Comment by quasemago** [comment]
@zeisaac Crie um novo issue para isso.
