### ISSUE TITLE
Problema no Slot

### ISSUE THREAD

**Issue by SCHROH** [quasemago/CSGO_WeaponStickers#16]
Eai mestre, estou com um probleminha, os stickers estão funcionando perfeitamente, mas o comando para adicionar em todos os slots não funciona, quando aplico o adesivo só fica no Slot 0 e os outros vazios,

Outra dúvida, tem como mudar o comando de !sticker para !adesivo? como faço? sou meio leigo, tenho esse server hospedado no meu pc mesmo só pra zuar com a galera... 

Vlw pelo plugin e obrigado desde já

**Comment by thegilaraujo** [comment]
> Eai mestre, estou com um probleminha, os stickers estão funcionando perfeitamente, mas o comando para adicionar em todos os slots não funciona, quando aplico o adesivo só fica no Slot 0 e os outros vazios,
> 
> Outra dúvida, tem como mudar o comando de !sticker para !adesivo? como faço? sou meio leigo, tenho esse server hospedado no meu pc mesmo só pra zuar com a galera...
> 
> Vlw pelo plugin e obrigado desde já

Olá! Tudo bem? A questão do slot eu não posso te auxiliar, pode ser algum bug ou você não seguiu todos os passos para a instalação correta do plugin.
Na questão de alterar comandos, eu acho que você precisa ir na pasta "csgo>addons>sourcemod>scripting>quasemago>csgo_weaponstickers>command.inc" e alterar a linha 3 e 4 para sm_adesivo ou sm_adesivos, depois é só salvar.

`RegConsoleCmd("sm_adesivo", Command_Stickers);

RegConsoleCmd("sm_adesivos", Command_Stickers);`

**Comment by quasemago** [comment]
Apos fazer o que o @thegilaraujo instruiu, recompile o plugin. Caso nao saiba fazer isso pesquise na wiki do sourcemod.

**Comment by SCHROH** [comment]
do comando tudo ok, dos slots infelizmente não consegui mudar, até reinstalei o mesmo, não há algum tipo de comando que posso verficiar ou inserir pra corrigir isso?

**Comment by quasemago** [comment]
Aqui funciona perfeitamente a opção "todos slots", ative a convar **"sm_weaponstickers_updateviewmodel"** e veja se resolve o problema.

**Comment by thegilaraujo** [comment]
> Aqui funciona perfeitamente a opção "todos slots", mas tente ativar a convar **"sm_weaponstickers_updateviewmodel"** e veja se resolve o problema.

Acho que deveria fechar essa issues por falta de interação @quasemago

**Comment by SCHROH** [comment]
Peço desculpa pela demora de feedback, estava muito atarefado na faculdade, mas a principio ok o comando, os stickers não consegui resolver deve ser algum bug do meu servidor. Obrigado pela ajuda.
