### ISSUE TITLE
Exception reported: Error fetching data from field 9

### ISSUE THREAD

**Issue by Z-RAY-Z** [quasemago/CSGO_WeaponStickers#19]
v1.0.13b
L 12/06/2020 - 23:07:07: [SM] Exception reported: Error fetching data from field 9
L 12/06/2020 - 23:07:07: [SM] Blaming: csgo_weaponstickers.smx
L 12/06/2020 - 23:07:07: [SM] Call stack trace:
L 12/06/2020 - 23:07:07: [SM]   [0] DBResultSet.FetchFloat
L 12/06/2020 - 23:07:07: [SM]   [1] Line 209, quasemago/csgo_weaponstickers/database.inc::SQLCallback_LoadClientData

**Comment by quasemago** [comment]
Are you sure you are using my version? because no field 9 is used.

Code:
https://github.com/quasemago/CSGO_WeaponStickers/blob/master/addons/sourcemod/scripting/quasemago/csgo_weaponstickers/database.inc#L165

**Comment by Z-RAY-Z** [comment]
Installed right version and cleaned DB. Works fine.
