### ISSUE TITLE
version 1.0.13c issues

### ISSUE THREAD

**Issue by ByKyTa** [quasemago/CSGO_WeaponStickers#20]
-> sm plugins reload csgo_weaponstickers
L 12/08/2020 - 19:58:29: [SM] Exception reported: Method "CEconItem::GetItemDefinition" was not loaded right.
L 12/08/2020 - 19:58:29: [SM] Blaming: modskin\csgo_weaponstickers.smx
L 12/08/2020 - 19:58:29: [SM] Call stack trace:
L 12/08/2020 - 19:58:29: [SM]   [0] SetFailState
L 12/08/2020 - 19:58:29: [SM]   [1] Line 318, csgo_weaponstickers.sp::LoadSDK
L 12/08/2020 - 19:58:29: [SM]   [2] Line 84, csgo_weaponstickers.sp::OnPluginStart

i try old version v1.0.12fix2 it working
My running os windows

**Comment by quasemago** [comment]
Make sure you use the updated **1.0.13c** gamedata. Everything is working on my test server.

**Comment by ByKyTa** [comment]
> Make sure you use the updated **1.0.13c** gamedata. Everything is working on my test server.

Thanks u. It problem 1.0.13c gamedata
