### ISSUE TITLE
Does not save in mysql

### ISSUE THREAD

**Issue by azpnx** [quasemago/CSGO_WeaponStickers#21]
![image](https://user-images.githubusercontent.com/48140187/102019324-a84a0280-3d51-11eb-86aa-c82cbedfd69b.png)

![image](https://user-images.githubusercontent.com/48140187/102019340-be57c300-3d51-11eb-83d1-f2577024a142.png)

**Comment by andretunes** [comment]
Hello!

To try help you out, can you inform me if the console has anything?

**Comment by fipso** [comment]
Having the same issue aswell. Is there any command to enable debug logging ?

**Comment by andretunes** [comment]
Hi,
Does your console outputs anything?

**Comment by quasemago** [comment]
I use the plugin on my servers and the plugin works perfectly. Check your error logs and make sure your mysql user has the necessary permissions.

**Comment by fipso** [comment]
The user has access and my server log does not say anything about the addon.
