### ISSUE TITLE
Removes standard skins from inventory when applying stickers

### ISSUE THREAD

**Issue by crashzk** [quasemago/CSGO_WeaponStickers#23]
When we use the option to add stickers to our skins that we have in the inventory, the plugin removes the skins leaves the CSGO pattern with the stickers.

https://vimeo.com/522157757

Would it be possible to add the stickers to the skins of the players' inventory without removing the skins and leaving the default CSGO skins?

**Comment by z1ntex** [comment]
> Когда мы используем опцию добавления наклеек к нашим скинам, которые у нас есть в инвентаре, плагин удаляет скины, оставляя шаблон CSGO вместе со стикерами.
> 
> https://vimeo.com/522157757
> 
> Можно ли добавить стикеры в скины инвентаря игроков, не удаляя скины и не оставляя скины CSGO по умолчанию?

Try sm_weaponstickers_overrideview "0"

**Comment by crashzk** [comment]
> > Когда мы используем опцию добавления наклеек к нашим скинам, которые у нас есть в инвентаре, плагин удаляет скины, оставляя шаблон CSGO вместе со стикерами.
> > https://vimeo.com/522157757
> > Можно ли добавить стикеры в скины инвентаря игроков, не удаляя скины и не оставляя скины CSGO по умолчанию?
> 
> Try sm_weaponstickers_overrideview "0"

I will test it, but from what I could see it is recommended to leave **`sm_weaponstickers_overrideview "1"`** if you use any **`!ws`** plugin.

https://github.com/quasemago/CSGO_WeaponStickers/blob/3941d3b0d1becdf8ac1220314e9f475256df51fe/addons/sourcemod/scripting/csgo_weaponstickers.sp#L77

In any case, I return with the feedback.

**Comment by crashzk** [comment]
It worked, I didn't understand the P.S, but ok.
