### ISSUE TITLE
copiler fail

### ISSUE THREAD

**Issue by IZOcC** [quasemago/CSGO_WeaponStickers#8]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// csgo_weaponstickers.sp
//
// E:\SourcePawn\addons\sourcemod\scripting\csgo_weaponstickers.sp(30) : fatal error 183: cannot read from file: "eItems"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.09 sec
// ----------------------------------------

Press enter to exit ...

**Comment by quasemago** [comment]
Install all dependencies

**Comment by IZOcC** [comment]
I installed eItems, otherwise I wouldn't come to say it doesn't work :P

**Comment by quasemago** [comment]
The error is clear, you do not have the eItems include. Please review everything before creating an issue unnecessarily.
