### ISSUE TITLE
another problem i think

### ISSUE THREAD

**Issue by IZOcC** [quasemago/CSGO_WeaponStickers#9]
L 09/06/2020 - 18:57:27: [SM] Blaming: eItems.smx
L 09/06/2020 - 18:57:27: [SM] Call stack trace:
L 09/06/2020 - 18:57:27: [SM]   [0] ArrayList.Get
L 09/06/2020 - 18:57:27: [SM]   [1] Line 257, files/func.sp::GetWeaponDefIndexByClassName
L 09/06/2020 - 18:57:27: [SM]   [2] Line 572, files/natives.sp::Native_GetWeaponDefIndexByClassName
L 09/06/2020 - 18:57:27: [SM]   [4] eItems_GetWeaponDefIndexByClassName
L 09/06/2020 - 18:57:27: [SM]   [5] Line 208, E:\SourcePawn\addons\sourcemod\scripting\csgo_weaponstickers.sp::OnGiveNamedItemPre
L 09/06/2020 - 18:57:27: [SM]   [7] GivePlayerItem
L 09/06/2020 - 18:57:27: [SM]   [8] Line 67, c:\Users\xSLOW\Desktop\compilerV2\source\awponly.sp::SetWeapons
L 09/06/2020 - 18:57:28: [SM] Exception reported: Client 2 is not in game

[Weapon Stickers] This weapon is not valid for customizing stickers.

**Comment by quasemago** [comment]
Your log cut one line, so I can't figure out why the plugin failed.

**Comment by IZOcC** [comment]
[errors_20200907.log](https://github.com/quasemago/CSGO_WeaponStickers/files/5184200/errors_20200907.log)
Last log

**Comment by quasemago** [comment]
> Exception reported: Invalid index 0 (count: 0)

Your eItems did not load, download my fork release: https://github.com/quasemago/eItems/releases/download/0.10/eItems_0.10.zip

**Comment by IZOcC** [comment]
working, thx man <3
